plugins {
    id "net.fabricmc.fabric-loom" version "1.15-SNAPSHOT"
    id 'maven-publish'
}

ext {
    mod_version = '1.0.0'
    maven_group = 'com.aizistral.nochatrestrictions'
    archives_base_name = 'nochatrestrictions'

    minecraft_version = '26.1'
    loader_version = '0.18.4'
    fabric_version = '0.144.0+26.1'
}

version = mod_version
group = maven_group

base {
    archivesName = archives_base_name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "nochatrestrictions" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

repositories {
    maven {
        url "https://maven.fabricmc.net/"
    }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

processResources {
    inputs.property "version", version
    inputs.property "minecraft_version", minecraft_version
    inputs.property "loader_version", loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": version,
                "minecraft_version": minecraft_version,
                "loader_version": loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = archives_base_name
            from components.java
        }
    }
    repositories {
    }
}