# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

modVersion=Forge-MC1.17.1-v1.0.0
manifestVersion=1.17.1-v1.0.0